DROP VIEW IF EXISTS vw_user_permissions;
DROP TABLE IF EXISTS role_permission;
DROP TABLE IF EXISTS permission;
DROP TABLE IF EXISTS user_role;
DROP TABLE IF EXISTS role;
DROP TABLE IF EXISTS user_address;
DROP TABLE IF EXISTS user_profile;
DROP TABLE IF EXISTS users;
