POST http://localhost:8080/user
Content-Type: application/json

{
  "full_name": "John Doe",
  "password": "securepassword",
  "password_confirmation": "securepassword",
  "email": "johndoe@mail.com",
  "phone_number": "1234567890"
}

###

GET http://localhost:8080/user/1
Content-Type: application/json
Authorization: Bearer v2.local.uPWEATH0g6zyv_JGFuCKa8jIruhvoC54ORQrooATfS6zvtV9tTaumcTpZuhA2rfIdwaFUgu585UMr7FrSd93FBlL6vPAFZOjb8quA-RjV-orufpVNPKUP3uJGKsP-tLixCTI64P2LrXy9DPbmAB90tGDYBIw3lExg5I552ILK-6S8uSkPFnLw1tsVjCQiN2H1IJGXGC_9Oz0